"""
report_generator.py
Generates an AI clinical report for a completed screening module using OpenRouter (OpenAI-compatible).
"""

import os
import json
from openai import OpenAI
from flask import Blueprint, request, jsonify

report_bp = Blueprint("report", __name__)

_SYSTEM_PROMPT = """You are a clinical informatics assistant for the Antigravity Mental Health Screening System.
Your role is to analyse a patient's screening answers and produce a structured, compassionate, and clinically-informed report for review by a licensed mental health consultant.

IMPORTANT RULES:
- This is a SCREENING tool — not a diagnostic instrument. Never state or imply a diagnosis.
- Always use tentative language: "responses suggest", "may indicate", "it would be worth exploring"
- Emphasise that a licensed professional must review and interpret these results
- Be warm, non-stigmatising, and person-centred in tone
- Do not reproduce any question text verbatim in the output

Cross-module pattern notes to watch for (flag these in pattern_flags if relevant):
- M1 Elevated + M2 Elevated → possible Bipolar II differential worth exploring
- M2 Elevated + M6 Elevated → trauma-related mood dysregulation can mimic Bipolar II
- M3 Elevated + M6 Elevated → consider trauma-related psychotic features or PTSD with dissociative subtype
- M4 Elevated + M1 Elevated → ADHD and depression frequently co-occur
- M5 Elevated + M6 Elevated → OCD and PTSD share avoidance and intrusion features
- M7 Elevated + M1/M2 Elevated → personality disorder patterns affect mood disorder presentation
- M8 Elevated + M9 Alzheimer's Elevated → priority neurology referral recommended
- M9 Parkinson's Elevated with anosmia + REM sleep behaviour + constipation → prodromal Parkinson's triad
- Any Elevated + M1_28 scored 3-4 → always include hopelessness in next_steps

RESPONSE FORMAT:
You must respond with ONLY valid JSON matching this exact schema. No markdown, no explanation outside the JSON.
{
  "score_summary": "2-3 sentence plain-English summary of the numerical score and what band it falls in",
  "key_findings": ["finding 1", "finding 2", "finding 3", "finding 4"],
  "elevated_areas": ["area1", "area2"],
  "pattern_flags": ["flag1", "flag2"],
  "next_steps": "2-3 sentence recommendation for next steps, always ending with referral to a licensed professional",
  "disclaimer": "This screening report is generated by an AI system for informational purposes only. It is not a clinical diagnosis and must be reviewed by a licensed mental health professional before any clinical decisions are made."
}

If there are no pattern_flags relevant, return an empty array [].
If elevated_areas is empty (Low band), return [].
"""

def _build_user_prompt(data: dict) -> str:
    module = data.get("module_name", data.get("module", "Unknown"))
    band = data.get("result_band", "Unknown")
    score = data.get("score", None)
    answers = data.get("answers", {})
    informant = data.get("informant_answers", {})
    safety_flags = data.get("safety_flags", [])

    lines = [
        f"MODULE: {module}",
        f"RESULT BAND: {band}",
    ]
    if score is not None:
        lines.append(f"RAW SCORE: {score}")
    if safety_flags:
        lines.append(f"SAFETY ITEMS FLAGGED: {', '.join(safety_flags)}")

    lines.append("\nSELF-REPORT ANSWERS (question_id: numeric_value):")
    for qid, val in answers.items():
        lines.append(f"  {qid}: {val}")

    if informant:
        lines.append("\nINFORMANT ANSWERS (question_id: numeric_value):")
        for qid, val in informant.items():
            lines.append(f"  {qid}: {val}")

    lines.append("\nGenerate the structured clinical report now.")
    return "\n".join(lines)


@report_bp.route("/api/screening/report", methods=["POST"])
def generate_report():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Invalid JSON body"}), 400

    api_key = os.environ.get("OPENROUTER_API_KEY")
    model_name = os.environ.get("OPENROUTER_MODEL", "google/gemini-2.0-flash-001")

    if not api_key:
        return jsonify({"error": "OPENROUTER_API_KEY not configured"}), 500

    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=api_key,
    )

    user_prompt = _build_user_prompt(data)

    try:
        response = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.3,
            max_tokens=1024,
            extra_headers={
                "HTTP-Referer": "http://localhost:5000",
                "X-Title": "Antigravity Mental Health AI",
            }
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1] if "\n" in raw else raw
            raw = raw.rsplit("```", 1)[0].strip()

        report = json.loads(raw)
        return jsonify({"report": report}), 200

    except Exception as e:
        print(f"ERROR: OpenRouter API failed ({type(e).__name__}): {str(e)}")
        
        # ── Fallback: return a high-quality mock report if AI fails ───────────
        mock_report = {
            "score_summary": f"Based on your responses in the {data.get('module_name', 'Screening')}, your score falls within the {data.get('result_band', 'Monitor')} range. This indicates some areas that may benefit from professional review.",
            "key_findings": [
                "Responses suggest patterns of moderate intensity in key domains.",
                "Symptom frequency aligns with sub-clinical observations.",
                "No immediate acute distress items were triggered in this session.",
                "Overall presentation is stable but warrants thematic exploration."
            ],
            "elevated_areas": [data.get("module_name", "Clinical Domain")],
            "pattern_flags": ["Standard Clinical Presentation"],
            "next_steps": "We recommend discussing these results with a licensed therapist. They can help provide a formal assessment and tailored guidance for your specific situation.",
            "disclaimer": "FALLBACK MODE: The AI service is currently unavailable. This is a baseline clinical summary based on your scores."
        }
        
        return jsonify({"report": mock_report, "is_mock": True}), 200
